### ISSUE TITLE
Feature Request: Add option to only show specifc teams matches and Team logos

### ISSUE THREAD

**Issue by Feedy88** [buxxi/MMM-Liquipedia-Dota2#1]
Hey buxxi,

first off, thanks for the great MagicMirror Module. While setting up mine, I was surprised in a positive way, that someone took the effort to code a module for Dota 2.

I really like the Module overall but would like to get out two feature requests, feel free to split them.

One: It would be great if I could configure to only see upcoming matches if at least one team is from a spcified list in the config file.

Two: A nice addition would be to show the logos next to the Team name.

As I am not a developer myself I cannot just go ahead and do it but would be happy if I can help in any way.

Cheers,
Feedy88

**Comment by buxxi** [comment]
Hi,
thanks for using the module and for the suggestions.

- The first one should be easy to just provide a whitelist in the config, kind of annoying to have to update it when team changes name and such, but should be good enough.
- About team logos, that's something I wanted too when I first created the module. But I skipped it since I hit some annoying road blocks:
  1. You can't hotlink images from liquipedia and when developing the module I got IP-blocked a few times with excessive reloading, which the module probably would if it tried to bypass the hotlinking and downloading all the logos.
  2. Some of the logos there doesn't really look at all on black background

So I guess there would have to be an additional installation-step to fetch team logos (from somewhere else) and then map them to each team name.

**Comment by buxxi** [comment]
I've added both features, see the readme.

I may create a script to fetch all notable teams logos and make them work with a black background in the future, but for now there's a manual installation step of them.

**Comment by Feedy88** [comment]
Thanks a lot for the adaptions.

I have created a list of all notable team logos and was able to pull them all with wget. Still need renaming though but let me know if that would help, happy to provide the file.

**Comment by buxxi** [comment]
I'm fine, not using the logos myself for now, there's too much small adjustments I would need to do before I find them really usable myself so the script will be a bit more advanced.
- Find out the filename that should be used
- Detect if its a black logo and invert the colors (IG, EG, Liquid would not be visible if just used as they are)
- Remove the transparent padding from each logo

**Comment by buxxi** [comment]
@Feedy88 I uploaded a script in the repo (and added instructions in the readme) that does the three points I wrote about in the previous comment.
